name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.1
            testbench: "^8.0"
          - php: 8.2
            testbench: "^9.0" 
          - php: 8.3
            testbench: "^10.0"
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          
      - name: Install dependencies
        run: |
          composer require --dev orchestra/testbench:${{ matrix.testbench }} --no-update
          composer update --prefer-dist --no-interaction --no-progress --with-all-dependencies
          
      - name: Debug - Check all files exist
        run: |
          echo "=== Service Provider ==="
          cat src/CookieHttpServiceProvider.php
          echo "=== HttpCookieStore ==="
          cat src/HttpCookieStore.php
          echo "=== Test file ==="
          cat tests/CookieHttpTest.php
          
      - name: Run PHPUnit with full error details
        run: vendor/bin/phpunit --verbose --debug --stop-on-failure
