name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Don't cancel other jobs when one fails
      matrix:
        include:
          - php: 8.1
            testbench: "^8.0"
          - php: 8.2
            testbench: "^9.0" 
          - php: 8.3
            testbench: "^10.0"
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          
      - name: Validate composer.json
        run: composer validate --strict
        
      - name: Install dependencies
        run: |
          composer require --dev orchestra/testbench:${{ matrix.testbench }} --no-update
          composer install --prefer-dist --no-interaction --no-progress
          
      - name: List installed packages
        run: composer show
        
      - name: Run PHPUnit with verbose output
        run: vendor/bin/phpunit --verbose