name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php: 8.1
            tb: "^8.0"    # Testbench 8 → Laravel 9
          - php: 8.2
            tb: "^9.0"    # Testbench 9 → Laravel 10/11
          - php: 8.3
            tb: "^10.0"   # Testbench 10 → Laravel 12

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Pin Testbench ${{ matrix.tb }}
        run: composer require --dev orchestra/testbench:${{ matrix.tb }} --no-update

      - name: Install all dependencies
        run: composer update --with-all-dependencies --prefer-dist --no-interaction --no-progress

      - name: Run PHPUnit
        run: vendor/bin/phpunit
